name: Flutter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          
      - name: Get dependencies
        run: |
          wget -q -O - https://storage.googleapis.com/flutter_infra_public/releases/stable/linux/flutter_2.x.x-stable.tar.xz | tar -xJf -
          export PATH="$PATH:$HOME/flutter/bin"

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk

      - name: Build iOS app
        run: flutter build ios
